name: Deploy Golang Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      # ✅ Cache Go modules to speed up builds
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Golang application
        run: go build -o myapp ./DominosEffectChallenge/server/cmd

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.109.214.22 >> ~/.ssh/known_hosts

      - name: Deploy to Server (fast + background)
        run: |
          scp -C -o ConnectTimeout=10 ./myapp ubuntu@3.109.214.22:~/service-dependency/myapp
          ssh -o ConnectTimeout=10 ubuntu@3.109.214.22 "
            cd ~/service-dependency &&
            echo '🔹 Stopping old instance (if any)...' &&
            pkill myapp || true &&
            echo '🔹 Starting new version...' &&
            nohup ./myapp > myapp.log 2>&1 &
            sleep 3 &&
            pgrep -a myapp || echo '⚠️ myapp may not have started properly.'
          "
