# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go


name: Deploy Golang Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1' # Specify your Go version

      - name: Build Golang application
        run: go build -o myapp ./DominosEffectChallenge/server/cmd

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts
        env:
          SSH_HOST: your-server-ip

      - name: Deploy to Server
        run: |
          scp ./myapp user@your-server-ip:/path/to/destination/myapp
          ssh user@your-server-ip "sudo systemctl restart myapp"
        env:
          SSH_USER: your-server-username # Replace with your server's username
          SSH_HOST: your-server-ip # Replace with your server's IP or hostname
