# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go


name: Deploy Golang Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1' # Specify your Go version

      - name: Build Golang application
        run: go build -o myapp ./DominosEffectChallenge/server/cmd

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.109.214.22 >> ~/.ssh/known_hosts
        env:
          SSH_HOST: 3.109.214.22

      - name: Deploy to Server
        run: |
          scp ./myapp ubuntu@3.109.214.22:~/service-dependency/myapp
          ssh ubuntu@3.109.214.22 "cd ~/service-dependency &&
            pkill myapp || true &&
            nohup ./myapp > myapp.log 2>&1 &"
     
